horror = Subject.create(name: "Horror")
fantasy = Subject.create(name: "Fantasy")
fiction = Subject.create(name: "Fiction")
religious = Subject.create(name: "religious")
mystery = Subject.create(name: "Myster")
